export const posts = [
  {
    slug: "how-long-does-local-seo-take",
    title: "How Long Does Local SEO Actually Take to Work?",
    date: "April 22, 2026",
    dateISO: "2026-04-22",
    category: "Local SEO",
    readTime: "5 min read",
    excerpt: "Three months is the honest answer. But that word means different things at 60 days versus 6 months, and if I just say three months and leave it there, I'm not actually helping you.",
    content: [
      { type: "p", text: `Three months is the honest answer. But "working" means different things at 60 days versus 6 months, and if I just say three months and leave it there, I'm not actually helping you.` },
      { type: "h2", text: "The First 60 Days" },
      { type: "p", text: "This is foundation work. Your Google Business Profile gets fully built out. Citations get cleaned up across Yelp, Apple Maps, Bing, and the other directories Google cross-references when it's deciding whether to trust your business information. Your website gets on-page basics done right: title tags, header structure, location-specific content." },
      { type: "p", text: "None of this makes your phone ring immediately. But it all has to happen before anything else will." },
      { type: "p", text: "You will start seeing your GBP get more profile views. More direction requests. Maybe a few more calls from the profile itself. That's real. It's just not the full picture yet." },
      { type: "h2", text: "90 Days In" },
      { type: "p", text: `This is when things start moving. You're in the map pack for some searches, probably not your main keyword yet, but the related ones. A plumber in McKinney might start ranking for "emergency plumber McKinney TX" before they rank for "plumber McKinney." The long-tail terms come first. The competitive ones take longer.` },
      { type: "p", text: "Reviews matter a lot here. If you've been asking customers consistently since day one, you'll have 10 to 20 by now. That compound effect is real. Google treats a steady stream of recent reviews as a signal that your business is active and worth ranking." },
      { type: "h2", text: "6 Months" },
      { type: "p", text: "This is where you start owning your market. If you've been consistent, with monthly GBP posts, content targeting your keywords, citations clean, reviews coming in, you're now competing for the top 3 in the map pack on your core terms. Whether you land there depends on your competition and how long they've been at this." },
      { type: "callout", text: "Ready to start building your local search presence in North Dallas? See exactly what's included in our Local SEO service.", linkText: "View Local SEO", href: "/services/local-seo" },
      { type: "h2", text: "The Real Variable: Your Category and Your City" },
      { type: "p", text: "If you're a landscaper in Anna or Princeton, you can own the map pack in 60 to 90 days. Competition in those markets isn't deep yet. If you're an HVAC company in Frisco going up against businesses that have been doing SEO for three years, expect 6 to 12 months to get where you want to be." },
      { type: "p", text: "The businesses that see results fastest are the ones that start immediately, stay consistent, and actually answer their phones when the calls come in. Local SEO gets people to find you. Everything after that is on you." },
    ],
  },
  {
    slug: "gbp-mistakes-killing-your-local-rankings",
    title: "5 Google Business Profile Mistakes That Are Suppressing Your Rankings",
    date: "April 17, 2026",
    dateISO: "2026-04-17",
    category: "Local SEO",
    readTime: "4 min read",
    excerpt: "Most business owners set up their Google Business Profile once and forget about it. That's usually the problem.",
    content: [
      { type: "p", text: "Most business owners set up their Google Business Profile once and forget about it. That's usually the problem." },
      { type: "p", text: "GBP is not a directory listing you fill out one time. Google rewards active management. Here are the five mistakes we fix most often when we start working with a new client." },
      { type: "h2", text: "1. Wrong Primary Category" },
      { type: "p", text: `Your primary category is one of the strongest ranking signals Google uses for the map pack. If you're a general contractor doing mostly bathroom remodels, "General Contractor" as your primary category is probably hurting you. "Bathroom Remodeler" will get you in front of people actually searching for that work.` },
      { type: "p", text: "We've had clients jump noticeably in rankings just from fixing this one thing. Secondary categories matter too. List every service that applies." },
      { type: "h2", text: "2. Zero Posts in the Last 60 Days" },
      { type: "p", text: "Posting frequency signals to Google that your business is active. It's not a massive ranking factor on its own, but it adds up. We post for clients at minimum once a week. A photo of a recent job, a short service update, a seasonal note. It takes 10 minutes." },
      { type: "p", text: "Most businesses haven't posted in months. Some haven't posted in over a year." },
      { type: "h2", text: "3. Old or Stock Photos" },
      { type: "p", text: "Real photos of your business, your team, and your actual work perform better and signal authenticity. Stock images do the opposite. If your last photo upload was two years ago, Google notices. So do potential customers. Most people look at photos before they call a business." },
      { type: "h2", text: "4. Unmanaged Q&A" },
      { type: "p", text: "The Questions and Answers section on your GBP is public. Anyone can ask a question, and anyone can answer it, including people who get it wrong. We populate our clients' Q&A sections with the questions they actually get asked and answer them directly. If you're not doing this, someone else might be answering for you." },
      { type: "h2", text: "5. Not Responding to Reviews" },
      { type: "p", text: "Every review needs a response. Positive ones are easy. Negative ones are where most businesses make mistakes. A calm, specific, professional response to a 1-star review often impresses potential customers more than the negative review hurts you. People are watching how you handle it." },
      { type: "p", text: "The common thread across all five: your GBP performs better when you treat it like an active part of your marketing. Not something you built once." },
      { type: "callout", text: "We manage Google Business Profiles for North Dallas businesses as part of our Local SEO service. GBP optimization is included, not an add-on.", linkText: "See Local SEO Pricing", href: "/services/local-seo" },
    ],
  },
  {
    slug: "mckinney-businesses-losing-leads-after-hours",
    title: "Why McKinney Businesses Are Losing Leads After Hours (And the Fix Takes 10 Minutes)",
    date: "April 22, 2026",
    dateISO: "2026-04-22",
    category: "Lead Generation",
    readTime: "7 min read",
    excerpt: "You missed a call. The caller didn't leave a voicemail. They Googled your competitor and booked with them instead. That's not a hypothetical. It's happening to McKinney businesses every single night.",
    content: [
      { type: "p", text: "You missed a call. The caller didn't leave a voicemail. They Googled your competitor and booked with them instead. That's not a hypothetical. It's happening to McKinney businesses every single night. The fix is an automated missed call text-back: the moment someone hangs up without reaching you, they get a text from your business within seconds. Most leads respond. Most competitors don't have this." },
      { type: "h2", text: "The Call You Missed Already Went Somewhere Else" },
      { type: "p", text: "Let's be honest about something." },
      { type: "p", text: "Your phone rings at 7:14 PM on a Tuesday. You're at your kid's practice. You don't answer. The caller waits three seconds, hangs up, and opens Google again." },
      { type: "p", text: "They don't leave a voicemail. Nobody does anymore." },
      { type: "p", text: "And by the time you see the missed call Wednesday morning, they've already booked with someone else. Or they're still shopping and they've forgotten your name." },
      { type: "p", text: "This happens dozens of times a month to small businesses across McKinney, Frisco, Allen, and Plano. Not because the business is bad. Not because the service is bad. Just because nobody was there to answer." },
      { type: "p", text: "Here's the brutal truth: 62% of customers who can't reach a business on the first try will not call back. (Source: Invoca Call Intelligence Report, 2024). They move on. The lead is gone. And you never even knew it existed." },
      { type: "h2", text: "Why Voicemail Doesn't Save You" },
      { type: "p", text: `"But I have voicemail."` },
      { type: "p", text: "Sure. And according to a 2023 Zipwhip study, 80% of callers sent to voicemail don't leave a message. Especially if they're comparison shopping, which most service leads are." },
      { type: "p", text: "Think about how you behave when you call a restaurant or a contractor and get voicemail. Do you leave a message? Or do you just call the next result?" },
      { type: "p", text: "Your customers are doing the same thing." },
      { type: "p", text: "Voicemail was designed for a world where people had patience and loyalty to a single provider. That world doesn't exist anymore in North Dallas. There are three HVAC companies, four landscapers, and two med spas within five miles of your location who will pick up, or at least text back instantly." },
      { type: "h2", text: "What Missed Call Text-Back Actually Does" },
      { type: "p", text: "This isn't complicated tech. It's a simple automation that runs in the background 24/7. Here's the sequence:" },
      { type: "ol", items: [
        "Someone calls your business number",
        "You don't answer (or can't)",
        `Within 30 seconds, they receive a text from your business number: "Hey, sorry we missed you! We'd love to help. What can we assist you with today?"`,
        "The conversation happens in text, on their timeline, not yours",
        "The lead is captured, named, and sitting in your pipeline by the time you check your phone",
      ]},
      { type: "p", text: "That's it. No app to download. No staff to train. Just leads that don't disappear." },
      { type: "p", text: "The response rate on that first text? Studies from Elixir Solutions put it at roughly 40%, compared to less than 5% for voicemail callbacks. You're looking at 8x more lead recovery just by sending a text instead of hoping they call back." },
      { type: "callout", text: "We set up missed call text-back and full AI lead automation for McKinney and North Dallas businesses. Most clients are live within two weeks.", linkText: "See AI Automation", href: "/services/ai-automation" },
      { type: "h2", text: "The After-Hours Problem Is Bigger Than You Think" },
      { type: "p", text: "Most McKinney business owners assume the majority of their leads call during business hours." },
      { type: "p", text: "They're usually wrong." },
      { type: "p", text: "Service-based businesses in HVAC, plumbing, auto repair, med spas, salons, and real estate get a significant chunk of their inbound interest between 5 PM and 9 PM. That's when people get home, decompress, and finally deal with the thing they've been putting off all day." },
      { type: "p", text: "Your business is closed. Your phone is in your pocket. And your competitor's automated system just responded to their inquiry in under a minute." },
      { type: "p", text: "After-hours isn't edge-case anymore. It's prime time." },
      { type: "h2", text: "Why This Matters Specifically in North Dallas" },
      { type: "p", text: "McKinney, Frisco, Allen, Melissa, Anna. This corridor is growing fast. New residents, new businesses, new competition every month." },
      { type: "p", text: `The bar for "responsive" has gotten higher. Families moving up from Plano or relocating from out of state are used to instant digital responses. They Googled your business, saw your reviews, decided to call. The moment you don't answer, that decision starts to unravel.` },
      { type: "p", text: "You've done the hard work of getting found. Don't lose the lead at the finish line because no one was available at 7 PM." },
      { type: "h2", text: "What a Real Setup Looks Like" },
      { type: "p", text: "Here's a basic version you can have running this week." },
      { type: "p", text: `The trigger: Any missed call to your business line. The action: An automated SMS goes out within 30 seconds, something like: "Hi! This is [Business Name]. Sorry we missed your call, we want to make sure we help you out. What's going on? We'll get back to you shortly."` },
      { type: "p", text: "The follow-up: If they respond, the conversation routes to your phone. If they don't respond within an hour, a second automated message goes out. If they book, they're added to your calendar automatically." },
      { type: "p", text: "You set it once. It runs forever." },
      { type: "p", text: "At Clarion Solutions, we build this inside GoHighLevel, which also handles your calendar, pipeline, follow-up sequences, and review requests. Everything in one place. No duct tape." },
      { type: "h2", text: "What Happens When You Don't Have This" },
      { type: "p", text: "The math is simple and a little uncomfortable." },
      { type: "p", text: "Say you miss 20 calls a month after hours. That's probably conservative for a busy service business in McKinney." },
      { type: "p", text: "Without text-back: maybe 2-3 of those people call back. You convert 1-2 of them. With text-back: you recover 8-10 of those leads into a conversation. You convert 3-5." },
      { type: "p", text: "Now think about what a single job is worth in your business. One HVAC repair. One supercharger install. One set of veneers. One roofing estimate that closes." },
      { type: "p", text: "For most North Dallas service businesses, recovering two or three extra jobs a month from leads you were already getting covers everything. The automation runs in the background either way." },
      { type: "h2", text: "This Is Lead Gen, Not Just Customer Service" },
      { type: "p", text: "Some business owners think of missed call text-back as a nicety. Good customer service, sure, but not a core growth tool." },
      { type: "p", text: "That's the wrong frame." },
      { type: "p", text: "This is lead generation. You've already paid for that lead through your SEO, your Google Business Profile, your word-of-mouth reputation. The call was the conversion moment. Text-back is what saves that investment when the moment doesn't go perfectly." },
      { type: "p", text: "Every lead that calls your business has already decided they're interested. They just need someone to respond." },
      { type: "p", text: "Be the one who responds." },
      { type: "h2", text: "FAQ" },
      { type: "h3", text: "Q: Won't customers think it's weird to get a text right after calling?" },
      { type: "p", text: `No, and the data backs that up. Most people find it reassuring. It tells them their call registered and someone is paying attention. The key is keeping the message warm and human-sounding, not robotic. Skip the "Your inquiry has been received" language. Write it like a person sent it.` },
      { type: "h3", text: "Q: What if I'm a one-person operation? Is this overkill?" },
      { type: "p", text: "It's actually more important for solo operators. You can't answer every call when you're doing the work. This is the system that makes sure you never lose a lead because you were on a job. It's like having a receptionist who never takes a day off." },
      { type: "h3", text: "Q: How do I know if it's actually working?" },
      { type: "p", text: "Every conversation, every response, every lead gets logged. You'll see exactly how many missed calls triggered a text, how many people responded, and how many turned into booked appointments or paid jobs. If the ROI isn't there after 60 days, something's misconfigured. And that's fixable." },
    ],
  },
];

export function getPost(slug) {
  return posts.find((p) => p.slug === slug) ?? null;
}
