export const posts = [
  {
    slug: "how-long-does-local-seo-take",
    title: "How Long Does Local SEO Actually Take to Work?",
    date: "April 22, 2026",
    dateISO: "2026-04-22",
    category: "Local SEO",
    readTime: "8 min read",
    excerpt: "Most local SEO timelines are vague. Here's what to actually expect at 60 days, 90 days, and 6 months for North Dallas businesses, and the real variables that determine how fast you rank.",
    content: [
      { type: "p", text: `Three months is the honest answer. But "working" means different things at 60 days versus 6 months, and if I just say three months and leave it there, I'm not actually helping you. This breakdown covers what's happening at each stage, what metrics to watch, and the real factors that determine whether your timeline is 60 days or 12 months.` },
      { type: "h2", text: "The First 60 Days: Foundation Work" },
      { type: "p", text: "This is the stage where most of the invisible work happens. Your Google Business Profile gets fully built out with the right primary category, service areas, attributes, and photos. Citations get cleaned up across Yelp, Apple Maps, Bing, and the other directories Google cross-references when deciding whether to trust your business information. Your website gets on-page basics done correctly: title tags, header structure, location-specific content, and schema markup." },
      { type: "p", text: "None of this makes your phone ring immediately. But it all has to happen before anything else will. Think of it as laying the foundation before you build the house. You would not skip it, but you also would not expect to live in it yet." },
      { type: "p", text: "What you will start to see in the first 60 days: your GBP gets more profile views, more direction requests, and maybe a few more calls from the profile itself. That is real traction. It is just not the full picture yet." },
      { type: "h2", text: "90 Days In: Things Start Moving" },
      { type: "p", text: `This is when you start seeing map pack appearances for searches you were not showing up for before. Probably not your main keyword yet, but the related ones. A plumber in McKinney might start ranking for "emergency plumber McKinney TX" before they rank for "plumber McKinney." The long-tail terms come first. The competitive head terms take longer.` },
      { type: "p", text: "Review velocity matters a lot at this stage. If you have been consistently asking customers for reviews since day one, you will have 10 to 20 by the 90-day mark. That compound effect is real. Google treats a steady stream of recent reviews as a signal that your business is active, legitimate, and worth ranking." },
      { type: "p", text: "Organic rankings on your website should also be improving. Pages that were not appearing in search at all are now somewhere on page two or three. Not where you want to be, but moving in the right direction." },
      { type: "h2", text: "6 Months: Competing for Your Market" },
      { type: "p", text: "At six months with consistent work, competitive categories start to open up. Monthly GBP posts, content targeting your core keywords, citations clean and consistent, reviews coming in regularly. You are now competing for the top three in the map pack on your main terms. Whether you land there depends on your competition and how long they have been doing this." },
      { type: "p", text: "For less competitive categories in smaller markets, a new restaurant in Anna or a contractor in Melissa, you might be looking at map pack dominance in 60 to 90 days. For a crowded vertical in Frisco or Plano, 6 to 12 months is realistic for the most competitive terms." },
      { type: "p", text: "The difference between good and great at this stage is usually content volume. Businesses publishing consistent local content, blog posts, location pages, GBP updates, are pulling ahead of competitors who are just maintaining a profile." },
      { type: "callout", text: "Ready to start building your local search presence in North Dallas? See exactly what's included in our Local SEO service.", linkText: "View Local SEO", href: "/services/local-seo" },
      { type: "h2", text: "What 'Working' Actually Means" },
      { type: "p", text: "Before you measure your timeline, define what success looks like for your business. These are the signals we track for North Dallas clients:" },
      { type: "ol", items: [
        "Map pack appearances for target keywords (track with BrightLocal or Google Search Console)",
        "GBP profile views, direction requests, and call clicks (visible in your GBP dashboard)",
        "Organic search impressions and clicks (Google Search Console)",
        "Website traffic from organic sources (Google Analytics)",
        "Inbound calls and leads attributed to local search",
      ]},
      { type: "p", text: "Rankings are a means to an end, not the goal. A client ranking number three in the map pack for their top keyword but converting poorly needs a different fix than more SEO. A client with great organic traffic but zero GBP calls has a GBP optimization problem, not a rankings problem. Look at the full picture." },
      { type: "h2", text: "The Real Variable: Your Category and Your City" },
      { type: "p", text: "If you're a landscaper in Anna or Princeton, you can own the map pack in 60 to 90 days. Competition in those markets is not deep yet. If you're an HVAC company in Frisco going up against businesses that have been doing SEO for three years, expect 6 to 12 months to get where you want to be." },
      { type: "p", text: "Category competitiveness varies too. 'Dentist McKinney TX' is a hard keyword with multiple well-established practices all doing SEO. 'Pediatric occupational therapist McKinney TX' is a softer keyword that an optimized profile can break into much faster." },
      { type: "p", text: "The businesses that see results fastest are the ones that start immediately, stay consistent, and actually answer their phones when the calls come in. Local SEO gets people to find you. Everything after that is on you." },
      { type: "h2", text: "What Slows Down Results" },
      { type: "p", text: "Several factors extend your timeline beyond the baseline:" },
      { type: "ol", items: [
        "Inconsistent citation information. If your name, address, and phone number appear differently across directories, Google has trouble trusting your listing.",
        "No review strategy. If you are not actively asking customers for reviews, competitors who are will outpace you.",
        "Thin or missing website content. Google needs content to understand what you do and where you do it. A five-page site with no location-specific text is a hard rank.",
        "A newly registered domain. Brand new websites have a trust deficit with Google that takes time to close.",
        "Established competitors. Going up against businesses with three or four years of consistent SEO takes longer than going up against businesses that have done nothing.",
      ]},
      { type: "h2", text: "How to Get Results Faster" },
      { type: "p", text: "You cannot skip the timeline, but you can make the most of it:" },
      { type: "ol", items: [
        "Start immediately. Every month you wait is a month behind where you could be.",
        "Ask every customer for a review, every time. Build it into your follow-up process.",
        "Post to your GBP at least once a week. A photo of a completed job with the city name in the caption counts.",
        "Make sure your name, address, and phone number are identical everywhere they appear online.",
        "Publish location-specific content on your website consistently.",
      ]},
      { type: "p", text: "The businesses that hit results fastest treat local SEO as an active system, not a one-time setup. Every input compounds. The ones who start and stop are the ones who complain that it doesn't work." },
      { type: "h2", text: "Frequently Asked Questions" },
      { type: "h3", text: "Is local SEO a one-time thing or ongoing?" },
      { type: "p", text: "Ongoing. Local SEO is a system you maintain, not a project you complete. Once you stop, competitors catch up. The businesses at the top of the map pack for competitive terms in McKinney and Frisco have been consistently active for years." },
      { type: "h3", text: "How do I know if my SEO is working before I see calls?" },
      { type: "p", text: "Watch GBP insights first. Profile views, direction requests, and call clicks all show up in your Google Business Profile dashboard and will start moving before your rankings dramatically change. Organic impressions in Search Console are the second signal. Phone calls are the lagging indicator, but they follow the earlier signals." },
      { type: "h3", text: "Can I do local SEO myself?" },
      { type: "p", text: "Yes, especially in less competitive markets. The basics are learnable: claim your GBP, optimize your categories, build citations consistently, ask for reviews, post regularly. Where agencies like ours add value is in the content strategy, technical SEO, and the ability to execute all of it consistently without it becoming your second job." },
    ],
    faqItems: [
      { q: "Is local SEO a one-time thing or ongoing?", a: "Ongoing. Local SEO is a system you maintain, not a project you complete. Once you stop, competitors catch up. The businesses at the top of the map pack for competitive terms in McKinney and Frisco have been consistently active for years." },
      { q: "How do I know if my SEO is working before I see calls?", a: "Watch GBP insights first. Profile views, direction requests, and call clicks all show up in your Google Business Profile dashboard and will start moving before your rankings dramatically change. Organic impressions in Search Console are the second signal. Phone calls are the lagging indicator, but they follow the earlier signals." },
      { q: "Can I do local SEO myself?", a: "Yes, especially in less competitive markets. The basics are learnable: claim your GBP, optimize your categories, build citations consistently, ask for reviews, post regularly. Where agencies add value is in content strategy, technical SEO, and executing consistently without it becoming your second job." },
    ],
  },
  {
    slug: "gbp-mistakes-killing-your-local-rankings",
    title: "5 Google Business Profile Mistakes That Are Suppressing Your Rankings",
    date: "April 17, 2026",
    dateISO: "2026-04-17",
    category: "Local SEO",
    readTime: "8 min read",
    excerpt: "Your Google Business Profile might be quietly suppressing your local rankings. Here are the 5 most common GBP mistakes we fix for North Dallas businesses, and exactly how to correct each one.",
    content: [
      { type: "p", text: "Most business owners set up their Google Business Profile once and forget about it. That's usually the problem." },
      { type: "p", text: "GBP is not a directory listing you fill out one time. Google rewards active management and penalizes neglect. Here are the five mistakes we fix most often when we start working with a new client, plus two more that do not get talked about enough." },
      { type: "h2", text: "Why Your GBP Matters More Than Your Website for Local Search" },
      { type: "p", text: "For service businesses in McKinney, Frisco, Allen, and Plano, the local map pack drives more calls than organic website traffic in most categories. A customer searching 'HVAC repair near me' or 'dentist McKinney TX' is going to see the map pack first. If you are not in the top three, you are invisible for that search." },
      { type: "p", text: "Your GBP is the primary input Google uses to decide who lands in those three spots. Your website matters too, but for local searches with high commercial intent, GBP health and active management is the dominant factor. Getting it wrong costs you real revenue." },
      { type: "h2", text: "1. Wrong Primary Category" },
      { type: "p", text: `Your primary category is one of the strongest ranking signals Google uses for the map pack. If you're a general contractor doing mostly bathroom remodels, "General Contractor" as your primary category is probably hurting you. "Bathroom Remodeler" will get you in front of people actually searching for that work.` },
      { type: "p", text: "We have seen clients jump noticeably in rankings just from fixing this one thing. The fix takes two minutes once you know what category to switch to." },
      { type: "p", text: "Secondary categories matter too. Add every relevant service category to your profile. A plumbing company that also does water heater installation should have 'Water Heater Contractor' listed as a secondary category. More categories mean more searches you are eligible to appear for. There is no penalty for adding relevant secondary categories." },
      { type: "h2", text: "2. Zero Posts in the Last 60 Days" },
      { type: "p", text: "Posting frequency signals to Google that your business is active. It is not a massive ranking factor on its own, but it adds up over time. We post for clients at minimum once a week: a photo of a recent job, a short service update, a seasonal note. It takes 10 minutes." },
      { type: "p", text: "Most businesses we audit have not posted in months. Some have not posted in over a year. Their competitors who post weekly have a consistent freshness signal that compounds." },
      { type: "p", text: "Post types that perform well: before and after photos, job completion shots with the location mentioned in the caption, seasonal service reminders (HVAC tune-up before summer, roof inspection before storm season), and short video clips of your team working." },
      { type: "h2", text: "3. Old or Stock Photos" },
      { type: "p", text: "Real photos of your business, your team, and your actual work perform better than stock images on every metric. Google's systems can identify stock images. More importantly, potential customers can too, and they trust them less." },
      { type: "p", text: "If your last photo upload was two years ago, your profile looks abandoned. Most people look at photos before they call a business, especially for service work where they want to see what kind of operation they are dealing with." },
      { type: "p", text: "Minimum viable photo set for any service business: exterior of your location or vehicle, your team at work, and at least five examples of completed work. Update with new job photos monthly." },
      { type: "h2", text: "4. Unmanaged Q&A" },
      { type: "p", text: "The Questions and Answers section on your GBP is public. Anyone can ask a question, and anyone can answer it, including people who get the information wrong." },
      { type: "p", text: "We populate our clients' Q&A sections proactively with the questions they actually get asked and answer them directly: pricing range, service area, booking process, guarantees. If you are not doing this, you are leaving that section open to community answers that may be inaccurate." },
      { type: "p", text: "This section also gets indexed by Google. A well-written Q&A that includes your target keywords can contribute to your local search visibility on top of the trust signal it provides to potential customers." },
      { type: "h2", text: "5. Not Responding to Reviews" },
      { type: "p", text: "Every review needs a response. Positive ones are easy. Negative ones are where most businesses either ignore them or respond defensively, both of which hurt you." },
      { type: "p", text: "A calm, specific, professional response to a 1-star review often impresses potential customers more than the negative review hurts you. People are not just reading the review. They are watching how you handle it." },
      { type: "p", text: "Response cadence matters too. Responding to reviews within 48 hours signals to Google that the business is actively managed. Leaving reviews unanswered for weeks suggests the opposite." },
      { type: "h2", text: "Two More Mistakes We See Constantly" },
      { type: "p", text: "These did not make the top five only because they are slightly less common, but they still show up in most audits we run." },
      { type: "h3", text: "Incorrect Service Area Settings" },
      { type: "p", text: "If you set your service area too narrowly, you are invisible for searches from neighboring cities you actually serve. If you set it too broadly, Google may discount your local relevance for the city you care most about. The right setup matches your actual service territory, typically a 15 to 30 mile radius for most North Dallas service businesses." },
      { type: "h3", text: "Missing or Incomplete Services Section" },
      { type: "p", text: "The Services section on your GBP lets you list specific offerings with descriptions. Most businesses leave it empty or fill in one-line entries with no context. A fully built-out services section helps Google understand exactly what you do and surfaces your listing for more specific searches that your competitors are not optimizing for." },
      { type: "p", text: "The common thread across all seven: your GBP performs better when you treat it like an active part of your marketing, not something you built once." },
      { type: "callout", text: "We manage Google Business Profiles for North Dallas businesses as part of our Local SEO service. GBP optimization is included, not an add-on.", linkText: "See Local SEO Pricing", href: "/services/local-seo" },
      { type: "h2", text: "How to Audit Your GBP Right Now" },
      { type: "p", text: "Open your Google Business Profile manager and check five things:" },
      { type: "ol", items: [
        "Primary category: Is it your most specific and relevant service, not the broadest available option?",
        "Last post: Was it less than seven days ago?",
        "Photos: Were any uploaded in the last 30 days?",
        "Q&A: Have you proactively answered the top five questions customers ask you?",
        "Reviews: Have you responded to every review received in the last 90 days?",
      ]},
      { type: "p", text: "If any of these are missing, fix them today. Each one is a 10-minute task. Together, they represent most of the quick-win GBP work that actually moves rankings." },
      { type: "h2", text: "Frequently Asked Questions" },
      { type: "h3", text: "How often should I post to my GBP?" },
      { type: "p", text: "At minimum, once per week. Consistency matters more than frequency. A business posting once a week every week for six months is ahead of a business that posts five times in one week and then goes quiet for two months." },
      { type: "h3", text: "Does the number of reviews affect my GBP ranking?" },
      { type: "p", text: "Yes, both quantity and recency. A business with 80 reviews that received 10 in the last 30 days will generally outrank a business with 80 reviews that received none in the last year. Google treats review velocity as a signal of business activity and current customer satisfaction." },
      { type: "h3", text: "Can a competitor get my GBP suspended?" },
      { type: "p", text: "It does happen. Competitors can flag your listing for policy violations, and if Google reviews it and agrees, your listing can be suspended. The best protection is running a clean, fully compliant profile with accurate information. If you do get suspended, there is an appeal process, but it takes time. That is another reason active monitoring of your profile matters." },
    ],
    faqItems: [
      { q: "How often should I post to my GBP?", a: "At minimum, once per week. Consistency matters more than frequency. A business posting once a week every week for six months is ahead of a business that posts five times in one week and then goes quiet for two months." },
      { q: "Does the number of reviews affect my GBP ranking?", a: "Yes, both quantity and recency. A business with 80 reviews that received 10 in the last 30 days will generally outrank a business with 80 reviews that received none in the last year. Google treats review velocity as a signal of business activity and current customer satisfaction." },
      { q: "Can a competitor get my Google Business Profile suspended?", a: "It does happen. Competitors can flag your listing for policy violations, and if Google reviews it and agrees, your listing can be suspended. The best protection is running a clean, fully compliant profile with accurate information. If you do get suspended, there is an appeal process, but it takes time." },
    ],
  },
  {
    slug: "mckinney-businesses-losing-leads-after-hours",
    title: "Why McKinney Businesses Are Losing Leads After Hours (And the Fix Takes 10 Minutes)",
    date: "April 22, 2026",
    dateISO: "2026-04-22",
    category: "Lead Generation",
    readTime: "7 min read",
    excerpt: "Most McKinney businesses lose 15 to 20 leads per month to missed calls. Here's how a simple automated text-back recovers those leads within seconds, and what you need to set it up this week.",
    content: [
      { type: "p", text: "You missed a call. The caller didn't leave a voicemail. They Googled your competitor and booked with them instead. That's not a hypothetical. It's happening to McKinney businesses every single night. The fix is an automated missed call text-back: the moment someone hangs up without reaching you, they get a text from your business within seconds. Most leads respond. Most competitors don't have this." },
      { type: "h2", text: "The Call You Missed Already Went Somewhere Else" },
      { type: "p", text: "Let's be honest about something." },
      { type: "p", text: "Your phone rings at 7:14 PM on a Tuesday. You're at your kid's practice. You don't answer. The caller waits three seconds, hangs up, and opens Google again." },
      { type: "p", text: "They don't leave a voicemail. Nobody does anymore." },
      { type: "p", text: "And by the time you see the missed call Wednesday morning, they've already booked with someone else. Or they're still shopping and they've forgotten your name." },
      { type: "p", text: "This happens dozens of times a month to small businesses across McKinney, Frisco, Allen, and Plano. Not because the business is bad. Not because the service is bad. Just because nobody was there to answer." },
      { type: "p", text: "Here's the brutal truth: 62% of customers who can't reach a business on the first try will not call back. (Source: Invoca Call Intelligence Report, 2024). They move on. The lead is gone. And you never even knew it existed." },
      { type: "h2", text: "Why Voicemail Doesn't Save You" },
      { type: "p", text: `"But I have voicemail."` },
      { type: "p", text: "Sure. And according to a 2023 Zipwhip study, 80% of callers sent to voicemail don't leave a message. Especially if they're comparison shopping, which most service leads are." },
      { type: "p", text: "Think about how you behave when you call a restaurant or a contractor and get voicemail. Do you leave a message? Or do you just call the next result?" },
      { type: "p", text: "Your customers are doing the same thing." },
      { type: "p", text: "Voicemail was designed for a world where people had patience and loyalty to a single provider. That world doesn't exist anymore in North Dallas. There are three HVAC companies, four landscapers, and two med spas within five miles of your location who will pick up, or at least text back instantly." },
      { type: "h2", text: "What Missed Call Text-Back Actually Does" },
      { type: "p", text: "This isn't complicated tech. It's a simple automation that runs in the background 24/7. Here's the sequence:" },
      { type: "ol", items: [
        "Someone calls your business number",
        "You don't answer (or can't)",
        `Within 30 seconds, they receive a text from your business number: "Hey, sorry we missed you! We'd love to help. What can we assist you with today?"`,
        "The conversation happens in text, on their timeline, not yours",
        "The lead is captured, named, and sitting in your pipeline by the time you check your phone",
      ]},
      { type: "p", text: "That's it. No app to download. No staff to train. Just leads that don't disappear." },
      { type: "p", text: "The response rate on that first text? Studies from Elixir Solutions put it at roughly 40%, compared to less than 5% for voicemail callbacks. You're looking at 8x more lead recovery just by sending a text instead of hoping they call back." },
      { type: "callout", text: "We set up missed call text-back and full AI lead automation for McKinney and North Dallas businesses. Most clients are live within two weeks.", linkText: "See AI Automation", href: "/services/ai-automation" },
      { type: "h2", text: "The After-Hours Problem Is Bigger Than You Think" },
      { type: "p", text: "Most McKinney business owners assume the majority of their leads call during business hours." },
      { type: "p", text: "They're usually wrong." },
      { type: "p", text: "Service-based businesses in HVAC, plumbing, auto repair, med spas, salons, and real estate get a significant chunk of their inbound interest between 5 PM and 9 PM. That's when people get home, decompress, and finally deal with the thing they've been putting off all day." },
      { type: "p", text: "Your business is closed. Your phone is in your pocket. And your competitor's automated system just responded to their inquiry in under a minute." },
      { type: "p", text: "After-hours isn't edge-case anymore. It's prime time." },
      { type: "h2", text: "Why This Matters Specifically in North Dallas" },
      { type: "p", text: "McKinney, Frisco, Allen, Melissa, Anna. This corridor is growing fast. New residents, new businesses, new competition every month." },
      { type: "p", text: `The bar for "responsive" has gotten higher. Families moving up from Plano or relocating from out of state are used to instant digital responses. They Googled your business, saw your reviews, decided to call. The moment you don't answer, that decision starts to unravel.` },
      { type: "p", text: "You've done the hard work of getting found. Don't lose the lead at the finish line because no one was available at 7 PM." },
      { type: "h2", text: "What a Real Setup Looks Like" },
      { type: "p", text: "Here's a basic version you can have running this week." },
      { type: "p", text: `The trigger: any missed call to your business line. The action: an automated SMS goes out within 30 seconds, something like: "Hi! This is [Business Name]. Sorry we missed your call, we want to make sure we help you out. What's going on? We'll get back to you shortly."` },
      { type: "p", text: "The follow-up: if they respond, the conversation routes to your phone. If they don't respond within an hour, a second automated message goes out. If they book, they're added to your calendar automatically." },
      { type: "p", text: "You set it once. It runs forever." },
      { type: "p", text: "At Clarion Solutions, we build this inside GoHighLevel, which also handles your calendar, pipeline, follow-up sequences, and review requests. Everything in one place." },
      { type: "h2", text: "What Happens When You Don't Have This" },
      { type: "p", text: "The math is simple and a little uncomfortable." },
      { type: "p", text: "Say you miss 20 calls a month after hours. That's probably conservative for a busy service business in McKinney." },
      { type: "p", text: "Without text-back: maybe 2 to 3 of those people call back. You convert 1 to 2 of them. With text-back: you recover 8 to 10 of those leads into a conversation. You convert 3 to 5." },
      { type: "p", text: "Now think about what a single job is worth in your business. One HVAC repair. One supercharger install. One set of veneers. One roofing estimate that closes." },
      { type: "p", text: "For most North Dallas service businesses, recovering two or three extra jobs a month from leads you were already getting covers everything. The automation runs in the background either way." },
      { type: "h2", text: "This Is Lead Gen, Not Just Customer Service" },
      { type: "p", text: "Some business owners think of missed call text-back as a nicety. Good customer service, sure, but not a core growth tool." },
      { type: "p", text: "That's the wrong frame." },
      { type: "p", text: "This is lead generation. You've already paid for that lead through your SEO, your Google Business Profile, your word-of-mouth reputation. The call was the conversion moment. Text-back is what saves that investment when the moment doesn't go perfectly." },
      { type: "p", text: "Every lead that calls your business has already decided they're interested. They just need someone to respond." },
      { type: "p", text: "Be the one who responds." },
      { type: "h2", text: "FAQ" },
      { type: "h3", text: "Q: Won't customers think it's weird to get a text right after calling?" },
      { type: "p", text: `No, and the data backs that up. Most people find it reassuring. It tells them their call registered and someone is paying attention. The key is keeping the message warm and human-sounding, not robotic. Skip the "Your inquiry has been received" language. Write it like a person sent it.` },
      { type: "h3", text: "Q: What if I'm a one-person operation? Is this overkill?" },
      { type: "p", text: "It's actually more important for solo operators. You can't answer every call when you're doing the work. This is the system that makes sure you never lose a lead because you were on a job. It's like having a receptionist who never takes a day off." },
      { type: "h3", text: "Q: How do I know if it's actually working?" },
      { type: "p", text: "Every conversation, every response, every lead gets logged. You'll see exactly how many missed calls triggered a text, how many people responded, and how many turned into booked appointments or paid jobs. If the ROI isn't there after 60 days, something's misconfigured. And that's fixable." },
    ],
    faqItems: [
      { q: "Will customers think it's weird to get a text right after calling?", a: "No, and the data backs that up. Most people find it reassuring. It tells them their call registered and someone is paying attention. The key is keeping the message warm and human-sounding, not robotic. Write it like a person sent it." },
      { q: "What if I'm a one-person operation? Is missed call text-back overkill?", a: "It's actually more important for solo operators. You can't answer every call when you're doing the work. This is the system that makes sure you never lose a lead because you were on a job. It's like having a receptionist who never takes a day off." },
      { q: "How do I know if missed call text-back is working?", a: "Every conversation, every response, and every lead gets logged. You'll see exactly how many missed calls triggered a text, how many people responded, and how many turned into booked appointments or paid jobs. If the ROI isn't there after 60 days, something's misconfigured." },
    ],
  },
  {
    slug: "how-to-rank-on-google-maps-mckinney-tx",
    title: "How to Get Your Business to Show Up on Google Maps in McKinney TX",
    date: "April 29, 2026",
    dateISO: "2026-04-29",
    category: "Local SEO",
    readTime: "7 min read",
    excerpt: "Showing up in Google Maps for McKinney and North Dallas searches comes down to six specific steps. Here's exactly what to do to get your business into the local map pack.",
    content: [
      { type: "definition", text: "Ranking on Google Maps means appearing in the local map pack, the three business listings Google shows above organic results for location-based searches. For McKinney and North Dallas businesses, map pack visibility directly drives phone calls, direction requests, and foot traffic from high-intent local customers." },
      { type: "p", text: "If you have ever searched for a business in McKinney and seen that cluster of three results with the map, that is the Google local map pack. Getting into it is the highest-value thing a local service business can do for its online presence. It drives more calls, more direction requests, and more conversions than most other digital marketing combined." },
      { type: "p", text: "Here is what actually moves the needle." },
      { type: "h2", text: "Step 1: Claim and Fully Verify Your Google Business Profile" },
      { type: "p", text: "If you have not claimed your GBP listing, that is the starting point. Go to business.google.com, search for your business, and claim it. Google will send a verification code, typically by postcard, to your business address." },
      { type: "p", text: "Once verified, fill out every single field. Business name, address, phone, website, hours, service areas, categories, attributes. The businesses that rank highest in the map pack are the ones that have given Google the most complete and accurate information to work with." },
      { type: "p", text: "The single most common mistake at this stage: using a tracking number instead of your real business phone number. Google cross-references your phone number across the web. If it does not match what is on your website and in other directories, that inconsistency hurts your rankings." },
      { type: "h2", text: "Step 2: Choose the Right Primary Category" },
      { type: "p", text: "Your primary category is the single strongest ranking signal in your GBP. Choose the most specific category that accurately describes your core service." },
      { type: "p", text: "A plumbing company should not use 'General Contractor' as their primary. A dentist should not use 'Health Professional.' Go as specific as the available categories allow. 'Emergency Plumber,' 'Cosmetic Dentist,' and 'HVAC Contractor' will outperform generic categories for the searches that actually convert." },
      { type: "p", text: "Add secondary categories for every additional relevant service. More categories mean more searches you are eligible to appear for. There is no penalty for adding relevant secondary categories. There is a real cost to leaving them empty." },
      { type: "h2", text: "Step 3: Build Consistent Citations Across the Web" },
      { type: "p", text: "A citation is any online mention of your business name, address, and phone number. Yelp, Apple Maps, Bing Places, Angi, Thumbtack, your local Chamber of Commerce, BBB. These are all citations." },
      { type: "p", text: "Google uses citation consistency as a trust signal. If your business name is listed as 'Acme Plumbing LLC' on your website, 'Acme Plumbing' on Yelp, and 'ACME Plumbing Services' on Bing, those inconsistencies make Google less confident about your business information." },
      { type: "p", text: "The goal is identical name, address, and phone number everywhere your business is listed. This sounds tedious because it is. But cleaning up citations is one of the highest-return tasks in local SEO, especially for businesses that have been operating for a few years and accumulated inconsistent listings." },
      { type: "h2", text: "Step 4: Get Reviews Consistently" },
      { type: "p", text: "Review quantity, recency, and rating all factor into map pack rankings. Google wants to surface businesses that customers trust and recommend. Reviews are the clearest signal they have." },
      { type: "p", text: "The businesses at the top of the McKinney map pack in most categories did not get there by accident. They built a system for asking every customer for a review and ran that system consistently for months." },
      { type: "p", text: "The easiest implementation: text every customer a review request link 24 hours after service completion. This can be automated. A 10% conversion rate on follow-up requests adds up fast. A business completing five jobs a day and asking every one for a review will accumulate 15 new reviews a month without any extra manual effort." },
      { type: "h2", text: "Step 5: Post to Your GBP Every Week" },
      { type: "p", text: "Google Business Profile posts are short updates that appear on your listing. They are not a major ranking factor in isolation, but they signal consistent activity, and Google rewards active profiles." },
      { type: "p", text: "Keep it simple. A photo of a completed job. A seasonal service reminder. An update about new hours or an upcoming closure. The format matters less than the consistency." },
      { type: "p", text: "Businesses that have been posting weekly for six months have a freshness signal their dormant competitors do not. Combined with strong reviews and complete profile information, it adds up to a real competitive advantage." },
      { type: "h2", text: "Step 6: Make Sure Your Website Backs Up Your GBP" },
      { type: "p", text: "Your website and your GBP need to be consistent and complementary. Google looks at both when deciding how to rank you in the map pack." },
      { type: "p", text: "Key signals on your website: your business name, address, and phone number match your GBP exactly. You have location-specific pages or content that mention the cities you serve. Your site loads quickly on mobile. You have LocalBusiness schema markup that confirms your location and service area." },
      { type: "p", text: "A strong GBP with a weak or inconsistent website is a common pattern we see in businesses that have invested in their GBP but never updated their site. Both need to be working together." },
      { type: "callout", text: "Want help getting your business into the Google Maps top three for McKinney and North Dallas searches? We handle the full setup and ongoing management.", linkText: "See Local SEO Service", href: "/services/local-seo" },
      { type: "h2", text: "How Long Does It Take to Show Up in Google Maps?" },
      { type: "p", text: "After claiming and optimizing your GBP, you will typically start seeing more profile activity within 30 days: more views, more direction requests, more calls from the profile itself. Map pack rankings for specific keywords take longer, usually 60 to 90 days for less competitive terms and 3 to 6 months for high-competition searches in markets like Frisco or Plano." },
      { type: "p", text: "The timeline shortens in proportion to how consistently you execute. Businesses that optimize their GBP, build citations, post weekly, and ask every customer for a review move faster than competitors who do one thing and stop." },
      { type: "h2", text: "Frequently Asked Questions" },
      { type: "h3", text: "Do I need a physical address in McKinney to rank in McKinney?" },
      { type: "p", text: "It helps significantly for the map pack. Google strongly favors businesses with a physical address inside the city they are ranking for. If you serve McKinney from a nearby city, you can still rank in organic results and set McKinney as part of your service area, but map pack rankings will be harder without an in-city address." },
      { type: "h3", text: "My competitor has fewer reviews than me but ranks higher. Why?" },
      { type: "p", text: "Reviews are one of many signals. Your competitor may have a more relevant primary category, stronger citation consistency, more complete profile information, or a website that is better optimized for local search. A ranking audit would tell you exactly where the gap is." },
      { type: "h3", text: "I claimed my GBP months ago but still do not show up. What is wrong?" },
      { type: "p", text: "Most commonly: the profile is not fully filled out, citations are inconsistent across the web, or the website does not support the GBP with local content and matching contact information. Less commonly: there is a verification issue or a policy compliance problem with the listing. A GBP audit would identify the specific problem." },
    ],
    howToSteps: [
      { name: "Claim and Fully Verify Your Google Business Profile", text: "Go to business.google.com, search for your business, and claim it. Fill out every field: business name, address, phone, website, hours, service areas, categories, and attributes." },
      { name: "Choose the Right Primary Category", text: "Select the most specific category that accurately describes your core service. Add secondary categories for every additional relevant service you offer." },
      { name: "Build Consistent Citations Across the Web", text: "List your business name, address, and phone number identically on Yelp, Apple Maps, Bing Places, Angi, and other directories Google uses as trust signals." },
      { name: "Get Reviews Consistently", text: "Text every customer a review request link 24 hours after service completion. A 10% conversion rate on follow-up requests builds review velocity that Google rewards." },
      { name: "Post to Your GBP Every Week", text: "Publish a short update weekly: a job photo, seasonal reminder, or service update. Consistent posting signals an active, trusted business to Google." },
      { name: "Make Sure Your Website Backs Up Your GBP", text: "Ensure your business name, address, and phone number match your GBP exactly. Add location-specific content, fast mobile load times, and LocalBusiness schema markup." },
    ],
    faqItems: [
      { q: "Do I need a physical address in McKinney to rank in McKinney on Google Maps?", a: "It helps significantly for the map pack. Google strongly favors businesses with a physical address inside the city they are ranking for. If you serve McKinney from a nearby city, you can still rank in organic results and set McKinney as part of your service area, but map pack rankings will be harder without an in-city address." },
      { q: "My competitor has fewer reviews than me but ranks higher in Google Maps. Why?", a: "Reviews are one of many signals. Your competitor may have a more relevant primary category, stronger citation consistency, more complete profile information, or a website that is better optimized for local search. A ranking audit would tell you exactly where the gap is." },
      { q: "I claimed my Google Business Profile months ago but still don't show up. What's wrong?", a: "Most commonly the profile is not fully filled out, citations are inconsistent across the web, or the website does not support the GBP with local content and matching contact information. Less commonly there is a verification issue or a policy compliance problem with the listing. A GBP audit would identify the specific problem." },
    ],
  },
  {
    slug: "ai-automation-for-small-business",
    title: "What Is AI Automation for Small Business? A Plain-English Guide",
    date: "April 24, 2026",
    dateISO: "2026-04-24",
    category: "AI Automation",
    readTime: "6 min read",
    excerpt: "AI automation for small businesses is not robots or complicated software. It's a set of tools that run in the background to capture leads, follow up with customers, and fill your calendar without extra staff.",
    content: [
      { type: "p", text: "When most business owners hear 'AI automation,' they think about large corporations with IT departments and million-dollar software budgets. That is not what we are talking about." },
      { type: "p", text: "For a service business in McKinney, Frisco, or Plano, AI automation is a set of tools that run in the background while you are doing the actual work. They capture leads you would otherwise miss, follow up with customers automatically, fill your calendar, and request reviews without you having to remember to do any of it." },
      { type: "p", text: "Here is what it actually looks like in practice." },
      { type: "h2", text: "What Business Automation Actually Means" },
      { type: "p", text: "Automation means replacing a manual, repetitive task with a system that handles it automatically. That is it. No robots. No complicated tech. Just tools that do things you are currently doing (or forgetting to do) by hand." },
      { type: "p", text: "For a service business, the highest-value automation targets are the tasks that happen around lead capture and customer communication: responding to inquiries, following up after quotes, confirming appointments, and requesting reviews. These are the things that fall through the cracks when you are busy doing the actual work." },
      { type: "h2", text: "The Core Automations That Move the Needle" },
      { type: "h3", text: "1. Missed Call Text-Back" },
      { type: "p", text: "When someone calls your business and you do not answer, they get an automated text within 30 seconds. The message is warm and conversational: 'Hey, sorry we missed you! What can we help you with?' Most leads respond. Most competitors do not have this." },
      { type: "p", text: "This is the highest-ROI automation for most service businesses because it recovers leads that are already lost. You have already done the marketing work to get them to call. Text-back is what saves that investment." },
      { type: "h3", text: "2. Automated Lead Follow-Up" },
      { type: "p", text: "Someone fills out a form on your website or sends an inquiry through Google. An automated sequence starts: an immediate response confirming you received their message, a follow-up text or email a few hours later, and additional touchpoints over the next few days if they have not booked yet." },
      { type: "p", text: "The average small business takes 47 hours to respond to an online inquiry. The businesses that respond within five minutes convert at eight times the rate. Automation makes five-minute responses possible at 11 PM without anyone staying up to watch the inbox." },
      { type: "h3", text: "3. Appointment Reminders and No-Show Reduction" },
      { type: "p", text: "A client books a service call for Thursday at 2 PM. Automated reminders go out: a confirmation text when they book, a reminder 24 hours before, and a reminder two hours before. If they need to reschedule, they reply to the text and it routes to your calendar." },
      { type: "p", text: "No-show rates for businesses using automated reminders drop significantly. The average reduction is around 30 to 50 percent, which for a service business running 15 to 20 appointments a week translates directly into recovered revenue." },
      { type: "h3", text: "4. Automated Review Requests" },
      { type: "p", text: "After a job is completed, an automated message goes to the customer 24 hours later asking them to leave a review, with a direct link to your Google Business Profile. A follow-up goes a few days later if they have not responded yet." },
      { type: "p", text: "This is how businesses accumulate 100, 200, 300 Google reviews over time without anyone manually tracking who to ask or remembering to follow up. The system handles it." },
      { type: "h3", text: "5. Pipeline Tracking and Lead Management" },
      { type: "p", text: "Every lead that comes in gets added to a pipeline automatically: new inquiry, contacted, quote sent, booked, completed, review requested. You open your dashboard and see exactly where every potential customer is in the process. Nothing falls through the cracks." },
      { type: "h2", text: "What Platform Does This Run On?" },
      { type: "p", text: "Most of these automations are built inside a CRM (Customer Relationship Management) platform. For service businesses in North Dallas, we primarily use GoHighLevel, which is built specifically for this kind of local service business workflow. It handles texting, email, calendar, pipeline management, and automation sequences all in one place." },
      { type: "p", text: "The technical setup is handled on our end. You see a clean dashboard, a shared inbox for all communications, and a calendar that fills itself. The platform runs in the background." },
      { type: "h2", text: "How Much Does Business Automation Cost?" },
      { type: "p", text: "A full AI automation system from Clarion Solutions starts at $1,500 per month. That includes the platform, setup, and ongoing management. No setup fee, cancel anytime." },
      { type: "p", text: "For most service businesses with an average job value of $300 or more, recovering two or three additional jobs per month from missed calls and faster follow-up more than covers the cost. Most clients see positive ROI within the first 60 days." },
      { type: "callout", text: "Ready to see what AI automation looks like for your specific business? We build and manage the full system for McKinney and North Dallas businesses.", linkText: "See AI Automation", href: "/services/ai-automation" },
      { type: "h2", text: "Is AI Automation Worth It for a Small Business?" },
      { type: "p", text: "The honest answer: it depends on how many leads you are currently losing to slow response times and missed calls." },
      { type: "p", text: "If you are a solo operator with a consistent referral pipeline and more work than you can handle, automation may not move the needle much right now. If you are a growing business getting 20 to 40 inbound inquiries a month and converting 30 to 40 percent of them, automation will recover a meaningful percentage of the leads you are missing." },
      { type: "p", text: "The easiest way to evaluate it: track your missed calls for one week. Count how many people you tried to call back and could not reach. That number multiplied by your average job value is roughly the revenue you are leaving on the table every week without a recovery system." },
      { type: "h2", text: "Frequently Asked Questions" },
      { type: "h3", text: "Does this replace my staff?" },
      { type: "p", text: "No. Automation handles repetitive communication tasks so your staff can focus on the work that requires a human. Think of it as giving your team a tool that handles the inbox at midnight, not replacing the people who show up to do the job." },
      { type: "h3", text: "Will customers know they are talking to an automation?" },
      { type: "p", text: "The initial response is automated, but it reads like a person sent it. Warm, brief, and direct. Once a customer replies, the conversation routes to your inbox and you or your staff take it from there. The goal is not to pretend a human is always available. It is to make sure no lead goes unanswered for hours." },
      { type: "h3", text: "How long does it take to set up?" },
      { type: "p", text: "Most clients are fully live within two weeks. That includes platform setup, automation build-out, number porting or setup, and a walkthrough training session. The ongoing management is handled by our team after that." },
    ],
    faqItems: [
      { q: "Does AI automation replace my staff?", a: "No. Automation handles repetitive communication tasks so your staff can focus on the work that requires a human. Think of it as giving your team a tool that handles the inbox at midnight, not replacing the people who show up to do the job." },
      { q: "Will customers know they are talking to an automation?", a: "The initial response is automated, but it reads like a person sent it. Warm, brief, and direct. Once a customer replies, the conversation routes to your inbox and you or your staff take it from there. The goal is to make sure no lead goes unanswered for hours, not to deceive anyone." },
      { q: "How long does it take to set up AI automation for a small business?", a: "Most clients are fully live within two weeks. That includes platform setup, automation build-out, number porting or setup, and a walkthrough training session. The ongoing management is handled by our team after that." },
    ],
  },
  {
    slug: "what-is-answer-engine-optimization",
    title: "What Is Answer Engine Optimization (AEO)?",
    date: "May 15, 2026",
    dateISO: "2026-05-15",
    category: "AEO",
    readTime: "9 min read",
    excerpt: "Answer engine optimization (AEO) is how you get your business cited in AI-generated answers from Google AI Overviews, ChatGPT, Perplexity, and similar platforms. Here is what it means, how it differs from traditional SEO, and what local businesses need to do to show up.",
    content: [
      { type: "definition", text: "Answer engine optimization (AEO) is the practice of structuring your website content so AI search platforms, including Google AI Overviews, ChatGPT, Perplexity, and Microsoft Copilot, extract and cite your business as the direct answer to relevant questions. Where traditional SEO gets you ranked in a list, AEO gets you cited as the answer itself." },
      { type: "p", text: "If you have searched something on Google recently and seen a large AI-generated response at the top of the page before the regular blue links, you have seen an AI Overview. That response was built by pulling content from websites Google considers credible and well-structured. Getting cited there is the goal of AEO." },
      { type: "p", text: "For McKinney and North Dallas businesses, this matters because AI-generated answers increasingly sit between a searcher and their decision. If an AI tells someone which local SEO agency to contact or which plumber in McKinney to call, the business cited in that answer wins the lead. The businesses not cited are invisible, regardless of how well they rank traditionally." },
      { type: "h2", text: "AEO vs SEO: What Is the Difference?" },
      { type: "p", text: "Traditional SEO and AEO are complementary disciplines, not competing ones. But they optimize for different outcomes and require different content approaches." },
      { type: "table", headers: ["Factor", "Traditional SEO", "Answer Engine Optimization"], rows: [
        ["Goal", "Rank in the blue-link results", "Get cited in AI-generated answers"],
        ["Primary signal", "Backlinks, authority, keywords", "Answer clarity, structure, authority"],
        ["User action required", "User clicks your link", "AI cites you without a click required"],
        ["Content format", "Long-form, keyword-rich narrative", "Structured: definitions, steps, tables, FAQs"],
        ["Schema markup", "Helpful", "Critical for AI extraction"],
        ["Author credentials", "Nice to have", "Direct citation signal"],
        ["Results timeline", "3 to 6 months", "4 to 8 weeks for established sites"],
      ]},
      { type: "p", text: "The key distinction: SEO puts you in a position where the user decides to click. AEO puts you in a position where the AI decides to cite you. That is a fundamentally different game with different rules." },
      { type: "h2", text: "How AI Search Platforms Decide Who to Cite" },
      { type: "p", text: "AI platforms like Google AI Overviews, Perplexity, and ChatGPT are not randomly selecting sources. They are running a fast content evaluation to determine which source best answers the query being asked. Three factors dominate that evaluation." },
      { type: "h3", text: "Answer Clarity" },
      { type: "p", text: "AI systems extract content in chunks. If your page buries the answer to a question three scrolls deep in a wall of narrative text, the AI will not find it. If your page opens with a direct, self-contained definition or answer in the first 200 words, the AI can pull it cleanly." },
      { type: "h3", text: "Content Structure" },
      { type: "p", text: "Numbered steps, comparison tables, FAQ blocks, and definition boxes are citation magnets. These formats tell the AI exactly where the answer lives and let it extract a clean, complete response. Flowing narrative prose is harder to extract and often gets passed over in favor of structured content from competitors." },
      { type: "h3", text: "Domain and Author Authority" },
      { type: "p", text: "AI systems still weight credibility. A response from a named expert with a clear affiliation is more citable than an anonymous page. Domain authority still matters. Original research and specific data get cited more than generalities. Traditional SEO authority signals carry directly into the AI citation era." },
      { type: "h2", text: "What AEO-Optimized Content Looks Like" },
      { type: "p", text: "For a local business trying to show up in AI answers, the practical changes are at the content level, not the technical level. Here is the difference between a standard page and one built for AI citation." },
      { type: "h3", text: "Standard page structure" },
      { type: "p", text: "Keyword in the title, an introduction that builds context slowly, service descriptions in paragraph form, a contact CTA at the bottom. This structure was built to rank in 2018. It was not built to be cited by an AI in 2026." },
      { type: "h3", text: "AEO-optimized page structure" },
      { type: "p", text: "A direct definition block in the first 200 words that answers the core question. Numbered steps or a comparison table where the content calls for structure. An FAQ section with conversationally phrased questions that match how people actually ask AI assistants. Specific data points with named source attribution. Author name and credentials on every page. Schema markup confirming the content type to search engines." },
      { type: "h2", text: "How to Show Up in Google AI Overviews" },
      { type: "p", text: "Google AI Overviews pull from pages Google already ranks and trusts. That means AEO builds on your SEO foundation. You need both working together." },
      { type: "ol", items: [
        "Ensure Google can fully crawl your site: fast load times, clean HTML, no content hidden behind JavaScript rendering.",
        "Add a direct definition or answer in the first 200 words of any page targeting an informational query.",
        "Use FAQPage schema on any page with Q&A content and HowTo schema on any step-by-step guide.",
        "Write in specific, concrete language. Replace vague claims with data. Replace 'experts say' with named sources and years.",
        "Add named author attribution with credentials on every page and blog post.",
        "Build backlinks to the pages you want cited. Domain authority still matters for AI citation selection.",
      ]},
      { type: "callout", text: "Clarion Solutions builds AEO-optimized content and schema markup for North Dallas businesses targeting AI search visibility. It is included in every Local SEO engagement.", linkText: "See Local SEO Service", href: "/services/local-seo" },
      { type: "h2", text: "Does AEO Replace Traditional SEO?" },
      { type: "p", text: "No. They reinforce each other. A page with no domain authority will not get cited in AI Overviews regardless of how well it is structured. A page with high authority but poor structure will get passed over in favor of a better-organized competitor page." },
      { type: "p", text: "The businesses winning in AI search right now are doing both. They have the authority that comes from sustained SEO work, and they are restructuring their content to be extractable by AI systems. That combination is what creates durable AI visibility." },
      { type: "p", text: "For local businesses just starting out: do not wait until your SEO is finished before thinking about AEO. The structural improvements that help AI citation also help traditional rankings. Building them in from the start is more efficient than retrofitting later." },
      { type: "h2", text: "Frequently Asked Questions" },
      { type: "h3", text: "What is the difference between AEO and SEO?" },
      { type: "p", text: "SEO optimizes for ranking in traditional search results. AEO optimizes for being cited in AI-generated answers. SEO focuses on keywords and backlinks. AEO focuses on answer structure, direct definitions, and schema markup. You need both for complete search visibility in 2026." },
      { type: "h3", text: "How long does AEO take to show results?" },
      { type: "p", text: "Structural improvements to existing pages can show up in AI Overviews within four to eight weeks if your domain already has authority. Brand new sites with no authority will need to build SEO credibility first. AEO accelerates citation for sites that have already earned Google's trust." },
      { type: "h3", text: "Does my website need to be technically perfect to show up in AI Overviews?" },
      { type: "p", text: "Not perfect, but crawlable. AI bots need to be able to access your pages, your important content should not be hidden behind JavaScript rendering, and your pages should load quickly on mobile. These are the baseline requirements. Everything beyond that is about content structure and authority." },
    ],
    faqItems: [
      { q: "What is answer engine optimization?", a: "Answer engine optimization (AEO) is the practice of structuring website content so AI search platforms, including Google AI Overviews, ChatGPT, and Perplexity, extract and cite your business as the direct answer to relevant questions." },
      { q: "What is the difference between AEO and SEO?", a: "SEO optimizes for ranking in traditional search results. AEO optimizes for being cited in AI-generated answers. SEO focuses on keywords and backlinks. AEO focuses on answer structure, direct definitions, and schema markup. Both are necessary for complete search visibility." },
      { q: "How long does AEO take to show results?", a: "Structural improvements to existing pages can show up in AI Overviews within four to eight weeks if your domain already has authority. Brand new sites will need to build SEO credibility first before AI citation follows." },
      { q: "Does my website need to be technically perfect to show up in AI Overviews?", a: "Not perfect, but crawlable. AI bots need to be able to access your pages, content should not be hidden behind JavaScript, and pages should load quickly. These are the baseline technical requirements for AI citation." },
    ],
  },
];

export function getPost(slug) {
  return posts.find((p) => p.slug === slug) ?? null;
}
