export const posts = [
  {
    slug: "how-long-does-local-seo-take",
    title: "How Long Does Local SEO Actually Take to Work?",
    date: "April 22, 2026",
    dateISO: "2026-04-22",
    category: "Local SEO",
    readTime: "5 min read",
    excerpt: "Three months is the honest answer. But that word means different things at 60 days versus 6 months, and if I just say three months and leave it there, I'm not actually helping you.",
    content: [
      { type: "p", text: `Three months is the honest answer. But "working" means different things at 60 days versus 6 months, and if I just say three months and leave it there, I'm not actually helping you.` },
      { type: "h2", text: "The First 60 Days" },
      { type: "p", text: "This is foundation work. Your Google Business Profile gets fully built out. Citations get cleaned up across Yelp, Apple Maps, Bing, and the other directories Google cross-references when it's deciding whether to trust your business information. Your website gets on-page basics done right: title tags, header structure, location-specific content." },
      { type: "p", text: "None of this makes your phone ring immediately. But it all has to happen before anything else will." },
      { type: "p", text: "You will start seeing your GBP get more profile views. More direction requests. Maybe a few more calls from the profile itself. That's real. It's just not the full picture yet." },
      { type: "h2", text: "90 Days In" },
      { type: "p", text: `This is when things start moving. You're in the map pack for some searches — probably not your main keyword yet, but the related ones. A plumber in McKinney might start ranking for "emergency plumber McKinney TX" before they rank for "plumber McKinney." The long-tail terms come first. The competitive ones take longer.` },
      { type: "p", text: "Reviews matter a lot here. If you've been asking customers consistently since day one, you'll have 10 to 20 by now. That compound effect is real. Google treats a steady stream of recent reviews as a signal that your business is active and worth ranking." },
      { type: "h2", text: "6 Months" },
      { type: "p", text: "This is where you start owning your market. If you've been consistent — monthly GBP posts, content targeting your keywords, citations clean, reviews coming in — you're now competing for the top 3 in the map pack on your core terms. Whether you land there depends on your competition and how long they've been at this." },
      { type: "h2", text: "The Real Variable: Your Category and Your City" },
      { type: "p", text: "If you're a landscaper in Anna or Princeton, you can own the map pack in 60 to 90 days. Competition in those markets isn't deep yet. If you're an HVAC company in Frisco going up against businesses that have been doing SEO for three years, expect 6 to 12 months to get where you want to be." },
      { type: "p", text: "The businesses that see results fastest are the ones that start immediately, stay consistent, and actually answer their phones when the calls come in. Local SEO gets people to find you. Everything after that is on you." },
    ],
  },
  {
    slug: "gbp-mistakes-killing-your-local-rankings",
    title: "5 Google Business Profile Mistakes That Are Suppressing Your Rankings",
    date: "April 17, 2026",
    dateISO: "2026-04-17",
    category: "Local SEO",
    readTime: "4 min read",
    excerpt: "Most business owners set up their Google Business Profile once and forget about it. That's usually the problem.",
    content: [
      { type: "p", text: "Most business owners set up their Google Business Profile once and forget about it. That's usually the problem." },
      { type: "p", text: "GBP is not a directory listing you fill out one time. Google rewards active management. Here are the five mistakes we fix most often when we start working with a new client." },
      { type: "h2", text: "1. Wrong Primary Category" },
      { type: "p", text: `Your primary category is one of the strongest ranking signals Google uses for the map pack. If you're a general contractor doing mostly bathroom remodels, "General Contractor" as your primary category is probably hurting you. "Bathroom Remodeler" will get you in front of people actually searching for that work.` },
      { type: "p", text: "We've had clients jump noticeably in rankings just from fixing this one thing. Secondary categories matter too. List every service that applies." },
      { type: "h2", text: "2. Zero Posts in the Last 60 Days" },
      { type: "p", text: "Posting frequency signals to Google that your business is active. It's not a massive ranking factor on its own, but it adds up. We post for clients at minimum once a week. A photo of a recent job, a short service update, a seasonal note. It takes 10 minutes." },
      { type: "p", text: "Most businesses haven't posted in months. Some haven't posted in over a year." },
      { type: "h2", text: "3. Old or Stock Photos" },
      { type: "p", text: "Real photos of your business, your team, and your actual work perform better and signal authenticity. Stock images do the opposite. If your last photo upload was two years ago, Google notices. So do potential customers. Most people look at photos before they call a business." },
      { type: "h2", text: "4. Unmanaged Q&A" },
      { type: "p", text: "The Questions and Answers section on your GBP is public. Anyone can ask a question, and anyone can answer it — including people who get it wrong. We populate our clients' Q&A sections with the questions they actually get asked and answer them directly. If you're not doing this, someone else might be answering for you." },
      { type: "h2", text: "5. Not Responding to Reviews" },
      { type: "p", text: "Every review needs a response. Positive ones are easy. Negative ones are where most businesses make mistakes. A calm, specific, professional response to a 1-star review often impresses potential customers more than the negative review hurts you. People are watching how you handle it." },
      { type: "p", text: "The common thread across all five: your GBP performs better when you treat it like an active part of your marketing. Not something you built once." },
    ],
  },
  {
    slug: "local-seo-contractors-north-dallas",
    title: "Local SEO for Contractors: What Works in McKinney, Frisco, and Allen",
    date: "April 10, 2026",
    dateISO: "2026-04-10",
    category: "Local SEO",
    readTime: "6 min read",
    excerpt: "I work with contractors in North Dallas every week. The SEO dynamics in this market are specific, and generic advice doesn't always apply. Here's what actually moves the needle up here.",
    content: [
      { type: "p", text: "I work with contractors in North Dallas every week — roofers, HVAC, plumbers, remodelers. The SEO dynamics in this market are specific, and generic advice doesn't always apply here. This is what actually works." },
      { type: "h2", text: "The Map Pack Is Where the Calls Come From" },
      { type: "p", text: `When someone in Frisco searches "roofing company near me," they're clicking the map pack results. Not the organic listings below them. If you're not in the top 3 box, you're getting a fraction of the available traffic. Every SEO decision we make for contractors is aimed at getting you into that box and keeping you there.` },
      { type: "h2", text: "Reviews Are More Competitive Here Than Most Markets" },
      { type: "p", text: "McKinney, Frisco, Allen. These are high-income markets with buyers who research before they call anyone. Your competitors have reviews. The question is whether you have more of them, more recent ones, and whether you're responding. We've seen contractors move from nowhere in the map pack to the top 3 primarily from a focused review push combined with GBP cleanup." },
      { type: "p", text: "Build a system for asking. It doesn't need to be complicated — just ask every customer. Two new reviews a month compounds significantly over a year." },
      { type: "h2", text: "Real Location Pages, Not Templates" },
      { type: "p", text: "If you serve McKinney, Frisco, Allen, Plano, and the surrounding cities, you need a real page for each one. Not a page where someone swapped the city name into a template and called it done. Google knows the difference. So do the people reading it." },
      { type: "p", text: "A page for Frisco should talk about the Frisco market, the neighborhoods you work in, the types of projects common there. It should read like it was written by someone who actually works in that area. Because it should be." },
      { type: "h2", text: "Site Speed Is a Real Ranking Factor" },
      { type: "p", text: "We build contractor websites on Next.js for a reason. Core Web Vitals are a direct Google ranking signal. A site that loads in under 1.5 seconds will consistently beat one that loads in 4 seconds, everything else being equal. We've seen this play out directly for clients we moved off slow WordPress sites." },
      { type: "p", text: "Run your current site through Google PageSpeed Insights. If you're scoring under 70 on mobile, that's affecting your organic rankings right now." },
      { type: "h2", text: "What Doesn't Move the Needle for Contractors" },
      { type: "p", text: "Social media posts. Logo redesigns. Facebook ads when your GBP has 8 reviews and your site loads in 5 seconds. None of that is what Google looks at when deciding where to rank you in the map pack." },
      { type: "p", text: "The list is short: GBP, reviews, a fast website, location-specific content, and consistent citations. If you're a contractor in North Dallas and you're not showing up where you should be, there's usually a fixable reason. It's rarely a mystery." },
    ],
  },
];

export function getPost(slug) {
  return posts.find((p) => p.slug === slug) ?? null;
}
